### ISSUE TITLE
Certbot doesn't know «--no-eff-email» option on debian8

### ISSUE THREAD

**Issue by jhayet** [tisc0/letsHAP#1]
The script ends with error when trying «-re» option :
```
# letsHAP -re 'beep'
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert. 
certbot: error: unrecognized arguments: --no-eff-email
```

version:
certbot/jessie-backports,jessie-backports,jessie-backports,now 0.10.2-1~bpo8+1

**Comment by tisc0** [comment]
Hi Jo',
You're running a very old certbot's version.
You might workaround this by using by hand : 
`certbot register -m $yourEmailAdress`

**Comment by jhayet** [comment]
Indeed, jessie seems to have this version. I ll upgrade it.
Thanks.
