### ISSUE TITLE
Stuck with crt for haproxy

### ISSUE THREAD

**Issue by zenny** [tisc0/letsHAP#6]
Hi,

Happy midsummer! Wonderul script!

Trying to run haproxy and this script in alpine, however, there is a glitch that prevents from haproxy running:

```
[ALERT] 171/091157 (834) : Proxy 'https': no SSL certificate specified for bind '*:443' at [/etc/haproxy/haproxy.cfg:61] (use 'crt').
[ALERT] 171/091157 (834) : Fatal errors found in configuration.
 * start-stop-daemon: failed to start `/usr/sbin/haproxy'                                                                                                                                [ !! ]
 * ERROR: haproxy failed to start
```

The error appears even after following as of below, fyi:

1. Executed /usr/local/bin/letshap -r <email> succeeded.
2. Executed /usr/local/bin/letshap -a <domain> failed because hproxy is not running at the backend to listen to by the certbot:

```
Failed authorization procedure. lhotse-rproxy.prodocero.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://lhotse-rproxy.prodocero.com/.well-known/acme-challenge/_8d0zj26hJgGIaNV4Qz4fc_JjyGMMSaRIwBrAGuOcd8: Connection refused
```
where in haproxy (in nginx it is in the vhost directory) the .well-known/acme-challenge directory be located?

3. Relevant certs are intact in /etc/letsencrypt directory.
4. Manually created /etc/haproxy/ssl directory and chmodded to ' chmod -R o-rwx'

Did I miss something? What is path_beg in https://github.com/tisc0/letsHAP/blob/master/haproxy.cfg?

What is the format of the /etc/haproxy/ssl/ssl.list? Any working example appreciated. Thanks in advance.

Cheers,
/z

**Comment by zenny** [comment]
Solved by getting the first cert via http by commenting the frontend_https part and the haproxy server started.

Some documentation would be worthwhile for someone who gets confused. Shall write one for alpine.

```
$ service haproxy start
 * Starting haproxy ...                                                                                                                                                                  [ ok ]
$ /usr/local/bin/letsHAP -a lhotse-rproxy.prodocero.com
Let's create your cert for lhotse-rproxy.prodocero.com... OK
We need to update HAPROXY certlist now... 
Creating HAPROXY fullchain file for certname lhotse-rproxy.prodocero.com (full SAN : lhotse-rproxy.prodocero.com)... 
OK 
Adding line(s) in /etc/haproxy/ssl/ssl.lst... OK
```

Posted for historical purpose. @tisc0 Thanks for such a nifty script anyway!

**Comment by tisc0** [comment]
Thanks a lot for your feedback Zenny, much appreciated.
