### ISSUE TITLE
Multiple domains support?

### ISSUE THREAD

**Issue by zenny** [tisc0/letsHAP#7]
Hi,

I am trying to deploy letsHAP in the front of other webservers running separate lxc containers based on domain names. It looks like:

domain.A ----> serverA0 and serverA1 in the backend
domain.B ---> serverB0 
domain.C ---> serverC0, serverA1

DNS points to the same domains, but when trying to get certs for each domain with
```
/usr/local/bin/letsHAP -a domain.A, www.domain.A
/usr/local/bin/letsHAP -a domain.B, www.domain.B
and so on
```
I am getting 503 error:

```
$ /usr/local/bin/letsHAP -a blet.us,www.domain.A
Let's create your cert for domain.A,www.domain.A... NOK - exit
Failed authorization procedure. www.domain.A (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from https://www.domain.A/.well-known/acme-challenge/pNqBVNND5RhLdO_ixPdR7xKmzUGAc... [PUBLIC IP]: 503
```

I have got backend pointed to the relevant machines as described at https://unix.stackexchange.com/questions/166169/how-to-configure-haproxy-to-redirect-multiple-domain, fyi.

Any inputs appreciated!

Cheers,
/z

**Comment by tisc0** [comment]
Hi Zenny,
Thanks for your interest and contribution.
The error you get has nothing to do with the backend pointing of your (sub-)domains (and the way to do it in the link you gave is clean). 

The error you get is a letsencrypt/certbot error while trying to register your new domains, during the verification phase. 

As I saw earlier today you've been successfully registering your first domain and get your certificate(s).
I guess you kept the right conf for it in haproxy config, but do you have it both in http and https frontends ? 

```
        acl app_letsencrypt  path_beg   /.well-known/acme-challenge/
        use_backend bk-letsencrypt if app_letsencrypt
```
As far as I remember, certbot passes through https, but I forgot the precise behavior and the why :)

Hope it helps,

**Comment by zenny** [comment]
@tisc0 Thanks for your input. However, the backend servers does not seem to be reachable, getting 503 error (503 Service Unavailable\n No server is available to handle this request.). Haproxy stats shows that all the servers are running.

When I bypass haproxy server to reach the backend servers, the domains are reachable without a hitch as it was meant for, fyi.

Any ideas?

**Comment by zenny** [comment]
Just posted the related question at https://serverfault.com/questions/972508/wildcard-name-based-provisioning-in-haproxy-cfg with a link to this repo, fyi with the belief that some haproxy masters could come up with the solution. ;-)

**Comment by tisc0** [comment]
You Problem seems out of letsHAP scope. Closing the issue (I tried to help you on serverfault).

**Comment by zenny** [comment]
@tisc0 Appreciate that. You are on the spot that the backends were missing in the frontend-http. 

Thanks again for the great script and wonderful inputs.
