### ISSUE TITLE
Importing existing certs from another server

### ISSUE THREAD

**Issue by zenny** [tisc0/letsHAP#9]
HI again,

I rsynced (--aOPvz) all LE certs from an the backend server to the machine running letsHAP with Haproxy. The certs were issued for a domain (reinvent-your-career.org) and its subdomain (www.reinvent-your-career.org), and  multiple alias domains (career-checkup-clinic.com and www.career-checkup-clinic.com) pointing to the same site in a server running an nginx webserver by manually running:
```
# /usr/bin/letsencrypt certonly -n --text --agree-tos --expand --authenticator standalone --pre-hook "service nginx stop" --post-hook "service nginx start" --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --email postmaster@reinvent-your-career.org --domains www.reinvent-your-career.org --domains career-checkup-clinic.com --domains www.reinvent-your-career.org --domains www.career-checkup-clinic.com
```
A cron job is handling the renewal part at the moment. I tried to update the existing certs by running:
```
/usr/local/bin/letsHAP -ra
```

but they failed, maybe the issuee's email and modality of  do not match with the way letsHAP gets certs.

In order to use it with HAproxy and letHAP script, I have manually concatenated the certs and placed it in the related folders in /etc/letsencrypt/archive/ which was pretty time consuming.

Is there a way to make the old certs compatible with letsHAP's renewal mechanism without a need to revoke and reissue again manually? Your valuable inputs appreciated. Thanks and cheers,
/z

**Comment by tisc0** [comment]
Hi,
LetsHAP's managing certificates the way certbot does, since it uses it (meaning: in /etc/letsencrypt).
And it's just adding the fullchain_haproxy.pem file (as fas as I remember), the way HAProxy likes them :)

I'd also say that the format of your old certs has nothing to do with the renewal, but with HAProxy not being able to work with them.

So, I'm sure you [could have] made a little script to ease your pain... something like : 
```
letsarchdir='/etc/letsencrypt/archive'
for dir in $letsdir
do
  cat ${letsarchdir}/${dir}/fullchain.pem ${letsarchdir}/${dir}/privkey.pem > ${letsarchdir}/${dir}/fullchain_haproxy.pem
done

```
